'use client';
import {useEffect,useState, type FormEvent} from 'react';
import {House,Bell,ClipboardCheck,Lightbulb,Link2,Users,Plus,ArrowUpRight,ChevronRight,Check,Clock,Trash2,X,ChevronDown,ShieldCheck,Leaf,Menu,RotateCcw,Heart,Sparkles,Radio,Hash,Moon,Sun,Settings,BarChart3,LayoutDashboard} from 'lucide-react';
import DiscordSetup from './discord-setup';
type Item={id:string;kind:string;title:string;note:string;due:string|null;done:boolean;createdAt:string};
type TwitchConnection={connected:boolean;user?:{id:string;login:string;displayName:string;profileImageUrl:string}};
type View='Home'|'Reminders'|'My Stream'|'Idea pocket'|'Connections'|'Your team'|'Discord setup'|'Account settings';
type StreamTab='overview'|'checklist'|'analytics';
const navigation=[{name:'Home',icon:House},{name:'Reminders',icon:Bell},{name:'My Stream',icon:Radio},{name:'Idea pocket',icon:Lightbulb},{name:'Discord setup',icon:Hash},{name:'Connections',icon:Link2},{name:'Your team',icon:Users}] as const;
const kinds:Record<string,string>={'Reminders':'reminder','My Stream':'checklist','Idea pocket':'idea','Connections':'connection'};
function Beipi(){return <svg viewBox="0 0 210 190" role="img" aria-label="B.E.I.P.I, your little purple companion"><ellipse cx="107" cy="174" rx="56" ry="8" fill="#dbd0f4"/><path d="M70 145L62 170H82L92 150M130 148L137 170H155L145 142" fill="#7255a9"/><path d="M145 125Q185 132 185 90Q201 144 148 152" fill="#baa3e9"/><path d="M63 116Q43 84 56 44Q74 9 114 18Q156 25 157 65L148 137Q133 163 95 158Q67 155 63 116" fill="#b99ae6"/><path d="M89 25Q88 9 102 8Q107 8 112 16" fill="none" stroke="#7255a9" strokeWidth="8" strokeLinecap="round"/><path d="M58 69Q96 38 143 54L150 84Q111 102 67 90Z" fill="#5c427f"/><ellipse cx="83" cy="72" rx="8" ry="11" fill="#e6fffa"/><ellipse cx="128" cy="69" rx="8" ry="11" fill="#e6fffa"/><path d="M92 83L114 81L105 99Z" fill="#f5ca8a"/><path d="M91 117Q108 108 125 116L123 143Q107 153 91 143Z" fill="#f1d9ff"/><path d="M69 104L46 111L54 128L75 118M146 103L166 113L156 128L137 117" fill="#9670c6"/><path d="M163 41L167 28M170 46L180 39M153 35L151 23" stroke="#ad8ccb" strokeWidth="3" strokeLinecap="round"/><path d="M38 59L40 52L42 59L49 61L42 63L40 70L38 63L31 61Z" fill="#c9a9e8"/><circle cx="180" cy="67" r="3" fill="#c9a9e8"/></svg>}
function TwitchLogo(){return <svg viewBox="0 0 24 24" role="img" aria-label="Twitch"><path fill="currentColor" d="M4 2h18v12.5L17 19.5h-4L10.5 22H7v-2.5H2V6l2-4Zm2 2L4 6v11.5h5V20l2.5-2.5H16l4-4V4H6Zm4 3h2v6h-2V7Zm5 0h2v6h-2V7Z"/></svg>}
function YouTubeLogo(){return <svg viewBox="0 0 24 24" role="img" aria-label="YouTube"><path fill="currentColor" d="M23.5 6.2a3 3 0 0 0-2.1-2.1C19.5 3.6 12 3.6 12 3.6s-7.5 0-9.4.5A3 3 0 0 0 .5 6.2 31 31 0 0 0 0 12a31 31 0 0 0 .5 5.8 3 3 0 0 0 2.1 2.1c1.9.5 9.4.5 9.4.5s7.5 0 9.4-.5a3 3 0 0 0 2.1-2.1A31 31 0 0 0 24 12a31 31 0 0 0-.5-5.8ZM9.6 15.6V8.4l6.3 3.6-6.3 3.6Z"/></svg>}
function DiscordLogo(){return <svg viewBox="0 0 24 24" role="img" aria-label="Discord"><path fill="currentColor" d="M19.5 5.3A16.3 16.3 0 0 0 15.4 4l-.5 1a15.1 15.1 0 0 0-5.8 0l-.5-1a16.5 16.5 0 0 0-4.1 1.3C1.9 9.2 1.2 13 1.5 16.8A16.8 16.8 0 0 0 6.6 19l1.2-1.7c-.7-.3-1.4-.6-2-1l.5-.4c3.8 1.8 7.8 1.8 11.5 0l.5.4c-.7.4-1.3.7-2 1l1.2 1.7a16.7 16.7 0 0 0 5.1-2.2c.4-4.4-.7-8.1-3.1-11.5ZM8.3 14.6c-1.1 0-2.1-1.1-2.1-2.5s.9-2.5 2.1-2.5 2.1 1.1 2.1 2.5-.9 2.5-2.1 2.5Zm7.4 0c-1.1 0-2.1-1.1-2.1-2.5s.9-2.5 2.1-2.5 2.1 1.1 2.1 2.5-.9 2.5-2.1 2.5Z"/></svg>}
const futurePlatforms=[
 {name:'YouTube',className:'youtube',mark:<YouTubeLogo/>,copy:'Your live channel, broadcasts and performance in one place.',note:'Google OAuth setup comes next'},
 {name:'TikTok',className:'tiktok',mark:<span>♪</span>,copy:'Connect your creator profile and prepare TikTok LIVE alerts.',note:'Developer approval will be required'},
 {name:'Kick',className:'kick',mark:<span>K</span>,copy:'Bring Kick streams and channel alerts into B.E.I.P.I.',note:'Secure connection planned'},
 {name:'Discord',className:'discord',mark:<DiscordLogo/>,copy:'Roles, live alerts and your community in one place.',note:'Discord OAuth setup planned'},
 {name:'Facebook',className:'facebook',mark:<span>f</span>,copy:'Keep Facebook streams visible alongside your other channels.',note:'Platform access to be reviewed'},
 {name:'Custom RTMP',className:'rtmp',mark:<Radio size={23}/>,copy:'Save another streaming destination or custom broadcast endpoint.',note:'Manual setup planned'}
];
export default function Dashboard(){
 const [discordDirty,setDiscordDirty]=useState(false);
 const [view,setView]=useState<View>('Home'),[streamTab,setStreamTab]=useState<StreamTab>('overview'),[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<string|null>(null),[filter,setFilter]=useState('open'),[menu,setMenu]=useState(false),[focus,setFocus]=useState(false),[dark,setDark]=useState(true);
 const [twitch,setTwitch]=useState<TwitchConnection>({connected:false}),[twitchLoading,setTwitchLoading]=useState(true);
 useEffect(()=>{const saved=window.localStorage.getItem('beipi-theme');if(saved)setDark(saved==='dark')},[]);
 useEffect(()=>{window.localStorage.setItem('beipi-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{fetch('/api/items').then(async r=>{const data=await r.json() as Item[] & {error?:string};if(!r.ok)throw Error(data.error);setItems(data)}).catch(e=>setError(e.message||'Could not load your notes. Please refresh.')).finally(()=>setLoading(false))},[]);
 useEffect(()=>{fetch('/api/auth/twitch/status',{cache:'no-store'}).then(r=>r.json()).then(data=>setTwitch(data as TwitchConnection)).catch(()=>setTwitch({connected:false})).finally(()=>setTwitchLoading(false));const result=new URLSearchParams(window.location.search).get('twitch');if(result==='connected')setToast('Twitch connected. B.E.I.P.I. found your channel!');if(result==='denied')setToast('Twitch connection was cancelled.');if(result==='error'||result==='invalid-state')setError('Twitch could not be connected. Please try again.')},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(id)},[toast]);
 useEffect(()=>{if(!dialog)return;function key(e:KeyboardEvent){if(e.key==='Escape')setDialog(null);if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.modal button:not(:disabled), .modal input, .modal textarea'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[dialog]);
 const open=items.filter(i=>!i.done),reminders=open.filter(i=>i.kind==='reminder'),checklist=items.filter(i=>i.kind==='checklist'),checked=checklist.filter(i=>i.done).length;
 async function request(method:string,body?:unknown,id?:string){setBusy(true);setError('');try{const r=await fetch('/api/items'+(id?'?id='+encodeURIComponent(id):''),{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json() as Item & {error?:string};if(!r.ok)throw Error(data.error);if(method==='POST')setItems(old=>[data,...old]);if(method==='PATCH')setItems(old=>old.map(i=>i.id===data.id?data:i));if(method==='DELETE')setItems(old=>old.filter(i=>i.id!==id));return true}catch(e){setError(e instanceof Error?e.message:'Something didn’t save. Please try again.');return false}finally{setBusy(false)}}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const due=String(form.get('due')||'');if(await request('POST',{kind:dialog,title:form.get('title'),note:form.get('note')||'',due:due?new Date(due+'T12:00:00').toISOString():null})){setDialog(null);setToast('Saved. You don’t have to hold that thought anymore.')}}
 async function toggle(item:Item){if(await request('PATCH',{id:item.id,done:!item.done}))setToast(item.done?'Back on your list.':'One less thing to remember. Nice work!')}
 async function template(){for(const title of ['Check microphone and game audio','Update stream title and category','Get water and take a breath'])if(!await request('POST',{kind:'checklist',title}))return;setToast('Your starter checklist is saved. Make it your own.')}
 async function resetChecklist(){for(const item of checklist.filter(i=>i.done))if(!await request('PATCH',{id:item.id,done:false}))return;setToast('Checklist reset. B.E.I.P.I. is ready for the next stream!')}
 async function disconnectTwitch(){setBusy(true);try{await fetch('/api/auth/twitch/disconnect',{method:'POST'});setTwitch({connected:false});setToast('Twitch disconnected.')}catch{setError('Twitch could not be disconnected. Please try again.')}finally{setBusy(false)}}
 const change=(name:View)=>{if(name===view)return;if(view==='Discord setup'&&discordDirty&&!confirm('Leave your unsaved Discord draft?'))return;setView(name);setFilter('open');setMenu(false)};
 const openMyStream=(tab:StreamTab)=>{setStreamTab(tab);change('My Stream')};
 function rows(list:Item[],compact=false){return <div className={'rows '+(compact?'compact':'')}>{list.map(item=><article className={'item '+(item.done?'completed':'')} key={item.id}><button className="check" aria-label={(item.done?'Reopen ':'Complete ')+item.title} disabled={busy} onClick={()=>toggle(item)}>{item.done&&<Check size={14}/>}</button><div className="item-text"><strong>{item.title}</strong>{item.note&&<p>{item.note}</p>}<small>{item.due?<><Clock size={12}/> {new Date(item.due).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</>:item.kind==='reminder'?'Whenever you’re ready':item.kind==='connection'?'Saved reference · Not connected':'Saved by you'}</small></div>{!compact&&<div className="item-actions">{item.kind==='reminder'&&!item.done&&<button title="Move reminder to tomorrow" aria-label={'Snooze '+item.title+' until tomorrow'} disabled={busy} onClick={()=>{const date=new Date();date.setDate(date.getDate()+1);void request('PATCH',{id:item.id,due:date.toISOString()}).then(ok=>ok&&setToast('Moved to tomorrow.'))}}><Clock size={16}/></button>}<button title="Delete" aria-label={'Delete '+item.title} disabled={busy} onClick={()=>{if(confirm('Delete this saved item?'))void request('DELETE',undefined,item.id)}}><Trash2 size={16}/></button></div>}</article>)}</div>}
 function empty(kind:string){return <div className="empty"><div className="empty-icon">{kind==='checklist'?<ClipboardCheck/>:kind==='idea'?<Lightbulb/>:<Leaf/>}</div><h3>{kind==='checklist'?'Your routine, your way.':kind==='idea'?'A home for your next good idea.':'A little space to breathe.'}</h3><p>{kind==='checklist'?'Save the things you like to check before going live.':kind==='idea'?'Stream ideas, games to try, little thoughts worth keeping.':'Nothing waiting here. Add a note whenever you need one.'}</p>{kind==='checklist'?<button className="primary" disabled={busy} onClick={()=>void template()}>Use a starter checklist <Plus size={16}/></button>:<button className="outline" onClick={()=>setDialog(kind)}>Add your first {kind==='idea'?'idea':'reminder'} <Plus size={16}/></button>}</div>}
 return <div className={'shell '+(focus?'focus-mode ':'')+(dark?'dark-theme':'light-theme')}>
 <aside className={menu?'sidebar visible':'sidebar'}><a href="/" className="brand"><span className="brand-mark">B<span>•</span></span><div>B.E.I.P.I<small>Your streaming companion</small></div></a><div className="workspace"><div className="workspace-icon">K</div><div><strong>The Kickaaverse</strong><small>Your private dashboard</small></div><ShieldCheck size={16}/></div><div className="nav-label">YOUR SPACE</div><nav>{navigation.map(({name,icon:Icon})=><button key={name} className={view===name?'active':''} onClick={()=>change(name)} aria-current={view===name?'page':undefined}><Icon size={19}/>{name}{name==='Reminders'&&reminders.length>0&&<span className="count">{reminders.length}</span>}{name==='Your team'&&<small className="soon">Soon</small>}</button>)}</nav><div className="sidebar-note"><Heart size={17}/><p>Less to remember.<br/><strong>More room to be you.</strong></p></div><button className={'profile '+(view==='Account settings'?'active':'')} onClick={()=>change('Account settings')}><div className="avatar">K</div><div><strong>Kickaa</strong><small>Account settings</small></div><Settings size={15}/></button></aside>
 <div className="body"><header className="topbar"><div className="crumb"><button className="mobile-menu" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}><Menu size={22}/></button><span>Your companion</span><ChevronRight size={14}/><strong>{view}</strong></div><div className="topbar-actions"><button className="quiet theme-toggle" onClick={()=>setDark(!dark)} aria-label={dark?'Switch to light mode':'Switch to dark mode'} title={dark?'Switch to light mode':'Switch to dark mode'}>{dark?<Sun size={15}/>:<Moon size={15}/>}<span>{dark?'Light mode':'Dark mode'}</span></button><button className={'quiet '+(focus?'selected':'')} onClick={()=>setFocus(!focus)} aria-pressed={focus}><Leaf size={15}/>{focus?'Show everything':'Focus view'}</button></div></header>
 <main><div className="page-heading"><div>{view==='Reminders'&&<div className="eyebrow">A LITTLE LESS TO HOLD IN YOUR HEAD</div>}<h1>{view==='Home'?'Welcome back, Kickaa.':view}</h1><p>{view==='Home'?'Pick up where you left off. One little thing at a time.':view==='Reminders'?'A gentle place for the things you want to remember.':view==='My Stream'?'Plan, prepare and understand your streams in one place.':view==='Idea pocket'?'Put it here before it disappears.':view==='Discord setup'?'Your banners, messages and reaction roles. One step at a time.':view==='Connections'?'Your streaming platforms, together in one place.':view==='Account settings'?'Your profile and dashboard preferences, all in one place.':'A little support from the people you trust.'}</p></div>{(['Reminders','Idea pocket','Connections'].includes(view)||(view==='My Stream'&&streamTab==='checklist'))&&<button className="primary" onClick={()=>setDialog(kinds[view]??'reminder')}><Plus size={17}/>{view==='Idea pocket'?'Save an idea':view==='My Stream'?'Add a step':view==='Connections'?'Save a channel':'Add a reminder'}</button>}</div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
 {loading?<div className="loading">B.E.I.P.I is finding your place…</div>:<>
 {view==='Home'&&<><section className="hero"><div className="hero-copy"><span className="pill"><Sparkles size={14}/> YOUR LITTLE CO-PILOT</span><h2>You bring the stream.<br/>I’ll help with the little things.</h2><p>Your tiny chaos coordinator—catching reminders,<br/>stream ideas and pre-live jobs before they wander off.</p><button onClick={()=>openMyStream('checklist')} className="hero-button">Let’s get stream-ready <ArrowUpRight size={17}/></button></div><div className="mascot"><Beipi/><span>Here when you need me. ♡</span></div></section>
 <div className="stats"><button onClick={()=>change('Reminders')}><span className="stat-icon lavender"><Bell size={20}/></span><div><strong>{reminders.length}</strong><span>Gentle reminders</span></div><ChevronRight size={17}/></button><button onClick={()=>openMyStream('checklist')}><span className="stat-icon mint"><ClipboardCheck size={20}/></span><div><strong>{checked}<small> / {checklist.length}</small></strong><span>Stream checks done</span></div><ChevronRight size={17}/></button><button onClick={()=>change('Idea pocket')}><span className="stat-icon peach"><Lightbulb size={20}/></span><div><strong>{open.filter(i=>i.kind==='idea').length}</strong><span>Ideas tucked away</span></div><ChevronRight size={17}/></button></div>
 <div className="home-grid"><section className="card"><div className="card-heading"><div><h2><Bell size={19}/> Your reminders</h2><p>No rush. Just a little nudge.</p></div><button className="text-button" onClick={()=>change('Reminders')}>See all <ArrowUpRight size={15}/></button></div>{reminders.length?rows(reminders.slice(0,3),true):empty('reminder')}</section><section className="card"><div className="card-heading"><div><h2><ClipboardCheck size={19}/> Before you go live</h2><p>Make a little room for a smoother start.</p></div><div className="card-heading-actions"><span className="subtle">{checked}/{checklist.length}</span><button className="text-button" disabled={busy||checked===0} onClick={()=>void resetChecklist()}><RotateCcw size={13}/> Reset after stream</button></div></div>{checklist.length?<><div className="progress"><span style={{width:100*checked/checklist.length+'%'}}/></div>{rows(checklist.slice(0,4),true)}<button className="text-button bottom-link" onClick={()=>openMyStream('checklist')}>Open your checklist <ArrowUpRight size={15}/></button></>:empty('checklist')}</section></div>
 <section className="connection-strip"><span className="stat-icon lavender"><Link2 size={21}/></span><div><h3>Your dashboard, taking shape.</h3><p>Your notes save here. Twitch, YouTube and Discord connections are the next step.</p></div><button className="outline" onClick={()=>change('Connections')}>View connections <ArrowUpRight size={16}/></button></section></>}
 {['Reminders','Idea pocket'].includes(view)&&<section className="card full"><div className="card-heading"><h2>{view==='Reminders'?'Your little nudges':'Keep that thought'}</h2><div className="tabs">{['open','done','all'].map(f=><button key={f} className={filter===f?'chosen':''} onClick={()=>setFilter(f)}>{f==='open'?'To do':f==='done'?'Done':'All'}</button>)}</div></div>{(()=>{const all=items.filter(i=>i.kind===kinds[view]);const list=all.filter(i=>filter==='all'||i.done===(filter==='done'));return list.length?rows(list):all.length?<div className="empty"><Check size={28}/><h3>{filter==='done'?'Nothing completed yet.':'You’re all caught up.'}</h3><p>Your saved items are still in the other tabs.</p></div>:empty(kinds[view])})()}</section>}
 {view==='My Stream'&&<><div className="stream-tabs" role="tablist" aria-label="My Stream sections"><button className={streamTab==='overview'?'chosen':''} onClick={()=>setStreamTab('overview')}><LayoutDashboard size={16}/> Overview</button><button className={streamTab==='checklist'?'chosen':''} onClick={()=>setStreamTab('checklist')}><ClipboardCheck size={16}/> Checklist</button><button className={streamTab==='analytics'?'chosen':''} onClick={()=>setStreamTab('analytics')}><BarChart3 size={16}/> Analytics</button></div>
 {streamTab==='overview'&&<><div className="stream-overview-grid"><section className="card stream-summary"><span className="stat-icon mint"><ClipboardCheck size={21}/></span><div><small>STREAM READINESS</small><h2>{checklist.length?Math.round(checked/checklist.length*100):0}% ready</h2><p>{checked} of {checklist.length} checklist steps complete.</p><button className="text-button" onClick={()=>setStreamTab('checklist')}>Open checklist <ArrowUpRight size={15}/></button></div></section><section className="card stream-summary"><span className="stat-icon lavender"><Link2 size={21}/></span><div><small>CONNECTED PLATFORMS</small><h2>{twitch.connected?1:0} connected</h2><p>{twitch.connected?'Twitch is ready for B.E.I.P.I.':'Connect Twitch to begin.'}</p><button className="text-button" onClick={()=>change('Connections')}>View connections <ArrowUpRight size={15}/></button></div></section></div><section className="card analytics-preview"><div><span className="eyebrow">YOUR STREAMING HOME</span><h2>Everything you need before you go live.</h2><p>Use your checklist now. Once platform analytics are connected, recent streams and performance highlights will appear here too.</p></div><Beipi/></section></>}
 {streamTab==='checklist'&&<section className="card full"><div className="card-heading"><h2>Your pre-stream routine</h2><div className="tabs">{['open','done','all'].map(f=><button key={f} className={filter===f?'chosen':''} onClick={()=>setFilter(f)}>{f==='open'?'To do':f==='done'?'Done':'All'}</button>)}</div></div>{checklist.length>0&&<div className="checklist-summary"><span>{checked} of {checklist.length} steps complete</span><button className="text-button" disabled={busy} onClick={()=>void resetChecklist()}><RotateCcw size={14}/> Reset for next stream</button></div>}{(()=>{const list=checklist.filter(i=>filter==='all'||i.done===(filter==='done'));return list.length?rows(list):checklist.length?<div className="empty"><Check size={28}/><h3>{filter==='done'?'Nothing completed yet.':'You’re all caught up.'}</h3><p>Your saved steps are still in the other tabs.</p></div>:empty('checklist')})()}</section>}
 {streamTab==='analytics'&&<section className="card full analytics-empty"><span className="stat-icon lavender"><BarChart3 size={24}/></span><h2>Your analytics will live here.</h2><p>Once more streaming platforms are securely connected, B.E.I.P.I. will bring your recent stream performance together without making the page feel overwhelming.</p><div className="analytics-placeholders"><span/><span/><span/><span/><span/><span/></div><button className="outline" onClick={()=>change('Connections')}>Manage connections <ArrowUpRight size={15}/></button></section>}</>}
 {view==='Discord setup'&&<DiscordSetup onDirty={setDiscordDirty}/>} 
 {view==='Connections'&&<><div className="notice"><Link2 size={20}/><div><strong>Connect the places where you create.</strong><p>Twitch is active. We’ll add each remaining secure connection carefully, one platform at a time.</p></div></div><div className="platform-grid"><section className="card platform"><span className="platform-icon twitch"><TwitchLogo/></span><span className={'status '+(twitch.connected?'connected':'')}>{twitchLoading?'Checking…':twitch.connected?'Connected':'Not linked'}</span><h2>Twitch</h2><p>{twitch.connected?<>Connected as <strong>{twitch.user?.displayName}</strong>. B.E.I.P.I. can recognise your Twitch channel.</>:'Live alerts for PC, PlayStation and Xbox broadcasts.'}</p>{twitch.connected?<button className="outline disconnect" disabled={busy} onClick={()=>void disconnectTwitch()}>Disconnect Twitch</button>:<a className="outline platform-connect twitch-connect" href="/api/auth/twitch/start"><TwitchLogo/> Connect with Twitch</a>}<small>{twitch.connected?`twitch.tv/${twitch.user?.login}`:'Secure sign-in through Twitch'}</small></section>{futurePlatforms.map(platform=><section className="card platform" key={platform.name}><span className={'platform-icon '+platform.className}>{platform.mark}</span><span className="status">Coming soon</span><h2>{platform.name}</h2><p>{platform.copy}</p><button className="outline" disabled>Connect {platform.name}</button><small>{platform.note}</small></section>)}</div><section className="card full"><div className="card-heading"><h2>Saved channel references</h2><span className="subtle">Private to you</span></div>{items.some(i=>i.kind==='connection')?rows(items.filter(i=>i.kind==='connection')):<div className="empty"><Link2 size={26}/><h3>No channel references yet.</h3><p>Your connected accounts and saved channel notes will appear here.</p></div>}</section></>}
 {view==='Your team'&&<><section className="team-hero card"><span className="stat-icon lavender"><Users size={25}/></span><h2>Your people. A little extra support.</h2><p>Your lead Twitch moderators will be able to leave private notes and reminders for you, with your permission.</p><span className="pill">Planned next · Access is not enabled</span></section><div className="team-steps">{['Sign in through Twitch','Connect their Discord account','Verify their moderator role','Get your approval to help'].map((t,i)=><div className="card" key={t}><span>{i+1}</span><h3>{t}</h3></div>)}</div><div className="notice"><ShieldCheck size={22}/><div><strong>You stay in control.</strong><p>No moderators can access this private dashboard yet. Team access, Twitch verification and shared reminders will be built next. Your saved notes are private.</p></div></div></>}
 {view==='Account settings'&&<section className="card full account-settings"><div className="account-intro"><div className="avatar account-avatar">K</div><div><h2>Kickaa</h2><p>The Kickaaverse · Dashboard owner</p></div></div><div className="setting-row"><div><strong>Appearance</strong><p>Choose the dashboard that feels easiest on your eyes.</p></div><button className="outline" onClick={()=>setDark(!dark)}>{dark?<Sun size={15}/>:<Moon size={15}/>} Switch to {dark?'light':'dark'} mode</button></div><div className="setting-row"><div><strong>Account access</strong><p>Google sign-in and permanent profiles will be connected in the account system update.</p></div><span className="status-inline">Coming next</span></div></section>}
 </>}
 <footer><span><Heart size={13}/> Made for brains with a few extra tabs open.</span><span>B.E.I.P.I · The streamer’s companion</span></footer>
 </main></div>{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 {dialog&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setDialog(null)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><button className="close" aria-label="Close dialog" disabled={busy} onClick={()=>setDialog(null)}><X size={20}/></button><span className="stat-icon lavender"><Plus size={23}/></span><h2 id="dialog-title">{dialog==='idea'?'Keep that thought.':dialog==='checklist'?'One little step.':dialog==='connection'?'Save a channel reference.':'Let’s remember this.'}</h2><p>{dialog==='connection'?'This saves a reference, not an account connection.':'It’ll be here when you come back.'}</p><form onSubmit={add}><label>{dialog==='connection'?'Channel or platform name':'What would you like to remember?'}<input name="title" maxLength={200} required autoFocus placeholder={dialog==='connection'?'Twitch · its_kickaa':'Give it a short, familiar name'}/></label><label>{dialog==='connection'?'Channel URL or details':'A little more detail (optional)'}<textarea name="note" maxLength={2000} rows={3} placeholder={dialog==='connection'?'https://twitch.tv/its_kickaa':'Anything that will help future you…'}/></label>{dialog==='reminder'&&<label>When? (optional)<input name="due" type="date"/><small>Dates appear on your dashboard. No notifications are sent yet.</small></label>}<div className="modal-actions"><button type="button" className="outline" disabled={busy} onClick={()=>setDialog(null)}>Not now</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save it for me'}<Check size={16}/></button></div>{error&&<p className="form-error" role="alert">{error}</p>}</form></section></div>}
 </div>
}
